# Example code : using multi layer perceptron

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("Datasets/Tweets.csv")

In [3]:
df.isna().sum()

tweet_id                            0
airline_sentiment                   0
airline_sentiment_confidence        0
negativereason                   5462
negativereason_confidence        4118
airline                             0
airline_sentiment_gold          14600
name                                0
negativereason_gold             14608
retweet_count                       0
text                                0
tweet_coord                     13621
tweet_created                       0
tweet_location                   4733
user_timezone                    4820
dtype: int64

In [4]:
df = df.drop(columns=['tweet_id','airline_sentiment_gold','name','negativereason_gold','text'])
df.sample(6)

,airline_sentiment,airline_sentiment_confidence,negativereason,negativereason_confidence,airline,retweet_count,tweet_coord,tweet_created,tweet_location,user_timezone
470,positive,1.0000,NaN,NaN,Virgin America,0,NaN,2015-02-17 14:09:03 -0800,NaN,NaN
11201,negative,0.6578,Late Flight,0.6578,US Airways,0,NaN,2015-02-19 07:56:00 -0800,NaN,NaN
3627,neutral,1.0000,NaN,NaN,United,0,NaN,2015-02-18 17:50:16 -0800,NaN,Eastern Time (US & Canada)
12399,negative,1.0000,Cancelled Flight,1.0000,American,0,NaN,2015-02-24 04:42:28 -0800,NaN,Eastern Time (US & Canada)
73,negative,1.0000,Flight Attendant Complaints,0.3516,Virgin America,0,NaN,2015-02-23 11:46:16 -0800,Los Angeles,NaN
14434,negative,1.0000,Flight Attendant Complaints,0.6702,American,0,NaN,2015-02-22 13:55:44 -0800,Chicago,Central Time (US & Canada)

In [5]:
import datetime as dt

In [6]:
df['tweet_created'] = pd.to_datetime(df['tweet_created'])
df['day_name'] = df['tweet_created'].dt.day_name()
df['tweet_created'] = df['tweet_created'].dt.date
df.sample(5)

,airline_sentiment,airline_sentiment_confidence,negativereason,negativereason_confidence,airline,retweet_count,tweet_coord,tweet_created,tweet_location,user_timezone,day_name
9375,neutral,1.0000,NaN,NaN,US Airways,0,NaN,2015-02-23,NaN,Eastern Time (US & Canada),Monday
12166,positive,1.0000,NaN,NaN,American,0,NaN,2015-02-24,NaN,Central Time (US & Canada),Tuesday
1172,negative,1.0000,Can't Tell,0.3442,United,0,NaN,2015-02-23,NaN,Quito,Monday
8563,neutral,1.0000,NaN,NaN,Delta,0,NaN,2015-02-18,NY,Quito,Wednesday
11970,negative,0.6463,Can't Tell,0.6463,American,0,NaN,2015-02-24,CA,Pacific Time (US & Canada),Tuesday

In [7]:
df.isna().sum().reset_index()

                           index      0
0              airline_sentiment      0
1   airline_sentiment_confidence      0
2                 negativereason   5462
3      negativereason_confidence   4118
4                        airline      0
5                  retweet_count      0
6                    tweet_coord  13621
7                  tweet_created      0
8                 tweet_location   4733
9                  user_timezone   4820
10                      day_name      0

In [8]:
pd.DataFrame({
    'NULL VALUES':df.isna().sum(),
    'UNIQUE VALUES':df.nunique(),
    'DTYPES':df.dtypes
})

                              NULL VALUES  UNIQUE VALUES   DTYPES
airline_sentiment                       0              3      str
airline_sentiment_confidence            0           1023  float64
negativereason                       5462             10      str
negativereason_confidence            4118           1410  float64
airline                                 0              6      str
retweet_count                           0             18    int64
tweet_coord                         13621            832      str
tweet_created                           0              9   object
tweet_location                       4733           3081      str
user_timezone                        4820             85      str
day_name                                0              7      str

In [9]:
# # printing only object and string data
df_str = df.select_dtypes(include='object').astype(str)

C:\Users\ashura\AppData\Local\Temp\ipykernel_2424\3630838830.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df_str = df.select_dtypes(include='object').astype(str)

In [10]:
# meging the string data into df
df.merge(df_str)
df.sample(5)

,airline_sentiment,airline_sentiment_confidence,negativereason,negativereason_confidence,airline,retweet_count,tweet_coord,tweet_created,tweet_location,user_timezone,day_name
2974,positive,0.6832,NaN,0.0000,United,0,NaN,2015-02-20,"ÜT: 40.635407,-73.991869",NaN,Friday
7215,positive,0.3606,NaN,0.0000,Delta,0,NaN,2015-02-23,"Cambridge, MA",Quito,Monday
2212,negative,1.0000,Can't Tell,1.0000,United,0,NaN,2015-02-21,"Columbus,Ohio",Eastern Time (US & Canada),Saturday
13911,negative,1.0000,Cancelled Flight,1.0000,American,0,NaN,2015-02-22,"Washington, DC",Atlantic Time (Canada),Sunday
5924,negative,1.0000,Flight Attendant Complaints,0.6525,Southwest,0,"[39.29372784, -94.71998281]",2015-02-19,NaN,Central Time (US & Canada),Thursday

In [11]:
pd.DataFrame({
    'NULL VALUES':df.isna().sum(),
    'UNIQUE VALUES':df.nunique(),
    'DTYPES':df.dtypes
})

                              NULL VALUES  UNIQUE VALUES   DTYPES
airline_sentiment                       0              3      str
airline_sentiment_confidence            0           1023  float64
negativereason                       5462             10      str
negativereason_confidence            4118           1410  float64
airline                                 0              6      str
retweet_count                           0             18    int64
tweet_coord                         13621            832      str
tweet_created                           0              9   object
tweet_location                       4733           3081      str
user_timezone                        4820             85      str
day_name                                0              7      str

In [12]:
df.select_dtypes(include='str')

,airline_sentiment,negativereason,airline,tweet_coord,tweet_location,user_timezone,day_name
0,neutral,NaN,Virgin America,NaN,NaN,Eastern Time (US & Canada),Tuesday
1,positive,NaN,Virgin America,NaN,NaN,Pacific Time (US & Canada),Tuesday
2,neutral,NaN,Virgin America,NaN,Lets Play,Central Time (US & Canada),Tuesday
3,negative,Bad Flight,Virgin America,NaN,NaN,Pacific Time (US & Canada),Tuesday
4,negative,Can't Tell,Virgin America,NaN,NaN,Pacific Time (US & Canada),Tuesday
...,...,...,...,...,...,...,...
14635,positive,NaN,American,NaN,NaN,NaN,Sunday
14636,negative,Customer Service Issue,American,NaN,Texas,NaN,Sunday
14637,neutral,NaN,American,NaN,"Nigeria,lagos",NaN,Sunday
14638,negative,Customer Service Issue,American,NaN,New Jersey,Eastern Time (US & Canada),Sunday
14639,neutral,NaN,American,NaN,"dallas, TX",NaN,Sunday

In [13]:
df['user_timezone'].unique().tolist()

['Eastern Time (US & Canada)',
 'Pacific Time (US & Canada)',
 'Central Time (US & Canada)',
 'America/New_York',
 'Atlantic Time (Canada)',
 'Quito',
 nan,
 'Mountain Time (US & Canada)',
 'Vienna',
 'Caracas',
 'Kuala Lumpur',
 'Brisbane',
 'Arizona',
 'London',
 'Tehran',
 'Alaska',
 'Sydney',
 'Irkutsk',
 'Santiago',
 'Amsterdam',
 'Tijuana',
 'Abu Dhabi',
 'Central America',
 'Edinburgh',
 'Jerusalem',
 'Hawaii',
 'Paris',
 'Guam',
 'New Delhi',
 'Stockholm',
 'America/Chicago',
 'Berlin',
 'Madrid',
 'Athens',
 'Brussels',
 'Taipei',
 'Rome',
 'Beijing',
 'Mexico City',
 'Bern',
 'Singapore',
 'Indiana (East)',
 'Melbourne',
 'Saskatchewan',
 'Casablanca',
 'Brasilia',
 'Kyiv',
 'Bucharest',
 'Greenland',
 'Prague',
 'New Caledonia',
 'Bogota',
 'Seoul',
 'Sarajevo',
 'Wellington',
 'Bangkok',
 'Warsaw',
 'Copenhagen',
 'Hong Kong',
 'Guadalajara',
 'Mid-Atlantic',
 'Mazatlan',
 'Buenos Aires',
 'America/Los_Angeles',
 'Dublin',
 'Lisbon',
 'Newfoundland',
 'Monterrey',
 'Tokyo',
 'America/Detroit',
 'Midway Island',
 'Istanbul',
 'Solomon Is.',
 'America/Atikokan',
 'Adelaide',
 'Nairobi',
 'EST',
 'Lima',
 'Islamabad',
 'Helsinki',
 'Pretoria',
 'West Central Africa',
 'America/Boise',
 'Canberra',
 'Perth',
 'La Paz']

In [14]:
user_timezone_fixes = {
    # Eastern Time Group
    'Eastern Time (US & Canada)': 'Eastern_Time',
    'America/New_York': 'Eastern_Time',
    'America/Detroit': 'Eastern_Time',
    'EST': 'Eastern_Time',
    'Indiana (East)': 'Eastern_Time',
    
    # Central Time Group
    'Central Time (US & Canada)': 'Central_Time',
    'America/Chicago': 'Central_Time',
    'Mexico City': 'Central_Time',
    'Guadalajara': 'Central_Time',
    'Monterrey': 'Central_Time',
    'Central America': 'Central_Time',
    
    # Mountain Time Group
    'Mountain Time (US & Canada)': 'Mountain_Time',
    'Arizona': 'Mountain_Time',
    'America/Boise': 'Mountain_Time',
    'Mazatlan': 'Mountain_Time',
    
    # Pacific Time Group
    'Pacific Time (US & Canada)': 'Pacific_Time',
    'America/Los_Angeles': 'Pacific_Time',
    'Tijuana': 'Pacific_Time',
    
    # Atlantic Group
    'Atlantic Time (Canada)': 'Atlantic_Time',
    'Newfoundland': 'Atlantic_Time'
}


df['user_timezone'] = df['user_timezone'].str.replace(r" \(US & Canada\)", "", regex=True)
df['user_timezone'] = df['user_timezone'].str.replace(" ", "_")

In [15]:
df['user_timezone'].unique()

<StringArray>
[          'Eastern_Time',           'Pacific_Time',           'Central_Time',
       'America/New_York', 'Atlantic_Time_(Canada)',                  'Quito',
                      nan,          'Mountain_Time',                 'Vienna',
                'Caracas',           'Kuala_Lumpur',               'Brisbane',
                'Arizona',                 'London',                 'Tehran',
                 'Alaska',                 'Sydney',                'Irkutsk',
               'Santiago',              'Amsterdam',                'Tijuana',
              'Abu_Dhabi',        'Central_America',              'Edinburgh',
              'Jerusalem',                 'Hawaii',                  'Paris',
                   'Guam',              'New_Delhi',              'Stockholm',
        'America/Chicago',                 'Berlin',                 'Madrid',
                 'Athens',               'Brussels',                 'Taipei',
                   'Rome',                'Beijing',            'Mexico_City',
                   'Bern',              'Singapore',         'Indiana_(East)',
              'Melbourne',           'Saskatchewan',             'Casablanca',
               'Brasilia',                   'Kyiv',              'Bucharest',
              'Greenland',                 'Prague',          'New_Caledonia',
                 'Bogota',                  'Seoul',               'Sarajevo',
             'Wellington',                'Bangkok',                 'Warsaw',
             'Copenhagen',              'Hong_Kong',            'Guadalajara',
           'Mid-Atlantic',               'Mazatlan',           'Buenos_Aires',
    'America/Los_Angeles',                 'Dublin',                 'Lisbon',
           'Newfoundland',              'Monterrey',                  'Tokyo',
        'America/Detroit',          'Midway_Island',               'Istanbul',
            'Solomon_Is.',       'America/Atikokan',               'Adelaide',
                'Nairobi',                    'EST',                   'Lima',
              'Islamabad',               'Helsinki',               'Pretoria',
    'West_Central_Africa',          'America/Boise',               'Canberra',
                  'Perth',                 'La_Paz']
Length: 86, dtype: str

In [16]:
pd.DataFrame({
    'NULL VALUES':df.isna().sum(),
    'UNIQUE VALUES':df.nunique(),
    'DTYPES':df.dtypes
})

                              NULL VALUES  UNIQUE VALUES   DTYPES
airline_sentiment                       0              3      str
airline_sentiment_confidence            0           1023  float64
negativereason                       5462             10      str
negativereason_confidence            4118           1410  float64
airline                                 0              6      str
retweet_count                           0             18    int64
tweet_coord                         13621            832      str
tweet_created                           0              9   object
tweet_location                       4733           3081      str
user_timezone                        4820             85      str
day_name                                0              7      str

In [17]:
df = df.drop(columns='tweet_location')

In [18]:
from sklearn.impute import KNNImputer
knn = KNNImputer(n_neighbors=10, weights='distance')

In [19]:
df.select_dtypes(include=['str']).columns

Index(['airline_sentiment', 'negativereason', 'airline', 'tweet_coord',
       'user_timezone', 'day_name'],
      dtype='str')

In [20]:
# using OHE
df_transformed = pd.get_dummies(df[['airline_sentiment', 'negativereason', 'airline', 'tweet_coord','user_timezone', 'day_name']])

In [27]:
nulls = df[['airline_sentiment', 'negativereason', 'airline', 'tweet_coord','user_timezone', 'day_name']].isna()
nulls.head(4)

,airline_sentiment,negativereason,airline,tweet_coord,user_timezone,day_name
0,False,True,False,True,False,False
1,False,True,False,True,False,False
2,False,True,False,True,False,False
3,False,False,False,True,False,False

In [30]:
df_transformed = df_transformed.astype(float)

# 2. Now run your loop
for col in ['airline_sentiment', 'negativereason', 'airline', 'tweet_coord', 'user_timezone', 'day_name']:
    temp_cols = [i for i in df_transformed.columns if i.startswith(col + '_')]
    df_transformed.loc[nulls[col], temp_cols] = np.nan

In [31]:
df_transformed

,airline_sentiment_negative,airline_sentiment_neutral,airline_sentiment_positive,negativereason_Bad Flight,negativereason_Can't Tell,negativereason_Cancelled Flight,negativereason_Customer Service Issue,negativereason_Damaged Luggage,negativereason_Flight Attendant Complaints,negativereason_Flight Booking Problems,...,user_timezone_Warsaw,user_timezone_Wellington,user_timezone_West_Central_Africa,day_name_Friday,day_name_Monday,day_name_Saturday,day_name_Sunday,day_name_Thursday,day_name_Tuesday,day_name_Wednesday
0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14635,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,0.0,0.0,1.0,0.0,0.0,0.0
14636,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,NaN,NaN,NaN,0.0,0.0,0.0,1.0,0.0,0.0,0.0
14637,0.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,0.0,0.0,1.0,0.0,0.0,0.0
14638,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
14639,0.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [36]:
num_cols = df.select_dtypes(include=['int','float']).columns.tolist()
num_cols

['airline_sentiment_confidence', 'negativereason_confidence', 'retweet_count']

In [37]:
data = pd.concat([df[num_cols], df_transformed], axis=1)

In [38]:
data.sample(6)

,airline_sentiment_confidence,negativereason_confidence,retweet_count,airline_sentiment_negative,airline_sentiment_neutral,airline_sentiment_positive,negativereason_Bad Flight,negativereason_Can't Tell,negativereason_Cancelled Flight,negativereason_Customer Service Issue,...,user_timezone_Warsaw,user_timezone_Wellington,user_timezone_West_Central_Africa,day_name_Friday,day_name_Monday,day_name_Saturday,day_name_Sunday,day_name_Thursday,day_name_Tuesday,day_name_Wednesday
12777,1.0000,0.6629,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
9668,1.0000,1.0000,0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,NaN,NaN,NaN,0.0,0.0,0.0,1.0,0.0,0.0,0.0
7832,1.0000,0.6842,0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0
7731,0.6747,NaN,0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
11057,0.6374,0.6374,0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
6099,0.6919,0.3594,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [39]:
knn = KNNImputer()

data_imputed = knn.fit_transform(data)

KeyboardInterrupt:

In [ ]:
a = pd.DataFrame(data_imputed, columns=data.columns, index=data.index)