# Example code : using multi layer perceptron

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("Datasets/Tweets.csv")

In [3]:
df.isna().sum()

tweet_id                            0
airline_sentiment                   0
airline_sentiment_confidence        0
negativereason                   5462
negativereason_confidence        4118
airline                             0
airline_sentiment_gold          14600
name                                0
negativereason_gold             14608
retweet_count                       0
text                                0
tweet_coord                     13621
tweet_created                       0
tweet_location                   4733
user_timezone                    4820
dtype: int64

In [4]:
df = df.drop(columns=['tweet_id','airline_sentiment_gold','name','negativereason_gold','text'])
df.sample(6)

,airline_sentiment,airline_sentiment_confidence,negativereason,negativereason_confidence,airline,retweet_count,tweet_coord,tweet_created,tweet_location,user_timezone
4287,positive,1.0000,NaN,NaN,United,0,"[40.35805521, -111.78241283]",2015-02-17 09:11:52 -0800,"Salt Lake City, Utah",Mountain Time (US & Canada)
4377,positive,0.3450,NaN,0.0,Southwest,0,NaN,2015-02-24 09:57:05 -0800,NaN,NaN
968,neutral,0.6825,NaN,NaN,United,0,NaN,2015-02-23 14:18:58 -0800,"Roatan, Islas de la Bahia",Eastern Time (US & Canada)
12236,neutral,1.0000,NaN,NaN,American,0,NaN,2015-02-24 08:16:04 -0800,"Wellesley, MA",Eastern Time (US & Canada)
3531,positive,0.6904,NaN,0.0,United,0,NaN,2015-02-18 22:08:02 -0800,NaN,Hawaii
5966,neutral,0.6444,NaN,NaN,Southwest,0,NaN,2015-02-19 08:57:49 -0800,NaN,Atlantic Time (Canada)

In [5]:
import datetime as dt

In [6]:
df['tweet_created'] = pd.to_datetime(df['tweet_created'])
df['day_name'] = df['tweet_created'].dt.day_name()
df['tweet_created'] = df['tweet_created'].dt.date
df.sample(5)

,airline_sentiment,airline_sentiment_confidence,negativereason,negativereason_confidence,airline,retweet_count,tweet_coord,tweet_created,tweet_location,user_timezone,day_name
5894,positive,1.0000,NaN,NaN,Southwest,0,NaN,2015-02-19,SEA,Pacific Time (US & Canada),Thursday
5673,neutral,0.6664,NaN,NaN,Southwest,0,NaN,2015-02-20,"Phoenix, Arizona",Central Time (US & Canada),Friday
4278,negative,1.0000,Cancelled Flight,1.0,United,0,NaN,2015-02-17,Usually in a plane,Eastern Time (US & Canada),Tuesday
13815,neutral,0.6799,NaN,0.0,American,0,NaN,2015-02-22,Leon. De los aldamas,Central Time (US & Canada),Sunday
5281,negative,1.0000,longlines,1.0,Southwest,0,NaN,2015-02-21,Bay Area,Pacific Time (US & Canada),Saturday

In [7]:
df.isna().sum().reset_index()

                           index      0
0              airline_sentiment      0
1   airline_sentiment_confidence      0
2                 negativereason   5462
3      negativereason_confidence   4118
4                        airline      0
5                  retweet_count      0
6                    tweet_coord  13621
7                  tweet_created      0
8                 tweet_location   4733
9                  user_timezone   4820
10                      day_name      0

In [8]:
pd.DataFrame({
    'NULL VALUES':df.isna().sum(),
    'UNIQUE VALUES':df.nunique(),
    'DTYPES':df.dtypes
})

                              NULL VALUES  UNIQUE VALUES   DTYPES
airline_sentiment                       0              3      str
airline_sentiment_confidence            0           1023  float64
negativereason                       5462             10      str
negativereason_confidence            4118           1410  float64
airline                                 0              6      str
retweet_count                           0             18    int64
tweet_coord                         13621            832      str
tweet_created                           0              9   object
tweet_location                       4733           3081      str
user_timezone                        4820             85      str
day_name                                0              7      str

In [9]:
# # printing only object and string data
df_str = df.select_dtypes(include='object').astype(str)

C:\Users\ashura\AppData\Local\Temp\ipykernel_13660\3630838830.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df_str = df.select_dtypes(include='object').astype(str)

In [10]:
# meging the string data into df
df.merge(df_str)
df.sample(5)

,airline_sentiment,airline_sentiment_confidence,negativereason,negativereason_confidence,airline,retweet_count,tweet_coord,tweet_created,tweet_location,user_timezone,day_name
2815,negative,1.0,Damaged Luggage,0.6383,United,1,NaN,2015-02-20,Chicago,Central Time (US & Canada),Friday
10174,negative,1.0,Customer Service Issue,0.6789,US Airways,0,NaN,2015-02-22,"Washington, DC",Eastern Time (US & Canada),Sunday
105,positive,1.0,NaN,NaN,Virgin America,0,NaN,2015-02-23,Online,Pacific Time (US & Canada),Monday
10331,negative,1.0,Late Flight,1.0000,US Airways,1,NaN,2015-02-21,Barneys New York,NaN,Saturday
9369,negative,1.0,Customer Service Issue,0.6682,US Airways,0,NaN,2015-02-23,NaN,Buenos Aires,Monday

In [11]:
pd.DataFrame({
    'NULL VALUES':df.isna().sum(),
    'UNIQUE VALUES':df.nunique(),
    'DTYPES':df.dtypes
})

                              NULL VALUES  UNIQUE VALUES   DTYPES
airline_sentiment                       0              3      str
airline_sentiment_confidence            0           1023  float64
negativereason                       5462             10      str
negativereason_confidence            4118           1410  float64
airline                                 0              6      str
retweet_count                           0             18    int64
tweet_coord                         13621            832      str
tweet_created                           0              9   object
tweet_location                       4733           3081      str
user_timezone                        4820             85      str
day_name                                0              7      str

In [12]:
df.select_dtypes(include='str')

,airline_sentiment,negativereason,airline,tweet_coord,tweet_location,user_timezone,day_name
0,neutral,NaN,Virgin America,NaN,NaN,Eastern Time (US & Canada),Tuesday
1,positive,NaN,Virgin America,NaN,NaN,Pacific Time (US & Canada),Tuesday
2,neutral,NaN,Virgin America,NaN,Lets Play,Central Time (US & Canada),Tuesday
3,negative,Bad Flight,Virgin America,NaN,NaN,Pacific Time (US & Canada),Tuesday
4,negative,Can't Tell,Virgin America,NaN,NaN,Pacific Time (US & Canada),Tuesday
...,...,...,...,...,...,...,...
14635,positive,NaN,American,NaN,NaN,NaN,Sunday
14636,negative,Customer Service Issue,American,NaN,Texas,NaN,Sunday
14637,neutral,NaN,American,NaN,"Nigeria,lagos",NaN,Sunday
14638,negative,Customer Service Issue,American,NaN,New Jersey,Eastern Time (US & Canada),Sunday
14639,neutral,NaN,American,NaN,"dallas, TX",NaN,Sunday

In [13]:
df['user_timezone'].unique().tolist()

['Eastern Time (US & Canada)',
 'Pacific Time (US & Canada)',
 'Central Time (US & Canada)',
 'America/New_York',
 'Atlantic Time (Canada)',
 'Quito',
 nan,
 'Mountain Time (US & Canada)',
 'Vienna',
 'Caracas',
 'Kuala Lumpur',
 'Brisbane',
 'Arizona',
 'London',
 'Tehran',
 'Alaska',
 'Sydney',
 'Irkutsk',
 'Santiago',
 'Amsterdam',
 'Tijuana',
 'Abu Dhabi',
 'Central America',
 'Edinburgh',
 'Jerusalem',
 'Hawaii',
 'Paris',
 'Guam',
 'New Delhi',
 'Stockholm',
 'America/Chicago',
 'Berlin',
 'Madrid',
 'Athens',
 'Brussels',
 'Taipei',
 'Rome',
 'Beijing',
 'Mexico City',
 'Bern',
 'Singapore',
 'Indiana (East)',
 'Melbourne',
 'Saskatchewan',
 'Casablanca',
 'Brasilia',
 'Kyiv',
 'Bucharest',
 'Greenland',
 'Prague',
 'New Caledonia',
 'Bogota',
 'Seoul',
 'Sarajevo',
 'Wellington',
 'Bangkok',
 'Warsaw',
 'Copenhagen',
 'Hong Kong',
 'Guadalajara',
 'Mid-Atlantic',
 'Mazatlan',
 'Buenos Aires',
 'America/Los_Angeles',
 'Dublin',
 'Lisbon',
 'Newfoundland',
 'Monterrey',
 'Tokyo',
 'America/Detroit',
 'Midway Island',
 'Istanbul',
 'Solomon Is.',
 'America/Atikokan',
 'Adelaide',
 'Nairobi',
 'EST',
 'Lima',
 'Islamabad',
 'Helsinki',
 'Pretoria',
 'West Central Africa',
 'America/Boise',
 'Canberra',
 'Perth',
 'La Paz']

In [14]:
user_timezone_fixes = {
    # Eastern Time Group
    'Eastern Time (US & Canada)': 'Eastern_Time',
    'America/New_York': 'Eastern_Time',
    'America/Detroit': 'Eastern_Time',
    'EST': 'Eastern_Time',
    'Indiana (East)': 'Eastern_Time',
    
    # Central Time Group
    'Central Time (US & Canada)': 'Central_Time',
    'America/Chicago': 'Central_Time',
    'Mexico City': 'Central_Time',
    'Guadalajara': 'Central_Time',
    'Monterrey': 'Central_Time',
    'Central America': 'Central_Time',
    
    # Mountain Time Group
    'Mountain Time (US & Canada)': 'Mountain_Time',
    'Arizona': 'Mountain_Time',
    'America/Boise': 'Mountain_Time',
    'Mazatlan': 'Mountain_Time',
    
    # Pacific Time Group
    'Pacific Time (US & Canada)': 'Pacific_Time',
    'America/Los_Angeles': 'Pacific_Time',
    'Tijuana': 'Pacific_Time',
    
    # Atlantic Group
    'Atlantic Time (Canada)': 'Atlantic_Time',
    'Newfoundland': 'Atlantic_Time'
}


df['user_timezone'] = df['user_timezone'].str.replace(r" \(US & Canada\)", "", regex=True)
df['user_timezone'] = df['user_timezone'].str.replace(" ", "_")

In [15]:
df['user_timezone'].unique()

<StringArray>
[          'Eastern_Time',           'Pacific_Time',           'Central_Time',
       'America/New_York', 'Atlantic_Time_(Canada)',                  'Quito',
                      nan,          'Mountain_Time',                 'Vienna',
                'Caracas',           'Kuala_Lumpur',               'Brisbane',
                'Arizona',                 'London',                 'Tehran',
                 'Alaska',                 'Sydney',                'Irkutsk',
               'Santiago',              'Amsterdam',                'Tijuana',
              'Abu_Dhabi',        'Central_America',              'Edinburgh',
              'Jerusalem',                 'Hawaii',                  'Paris',
                   'Guam',              'New_Delhi',              'Stockholm',
        'America/Chicago',                 'Berlin',                 'Madrid',
                 'Athens',               'Brussels',                 'Taipei',
                   'Rome',                'Beijing',            'Mexico_City',
                   'Bern',              'Singapore',         'Indiana_(East)',
              'Melbourne',           'Saskatchewan',             'Casablanca',
               'Brasilia',                   'Kyiv',              'Bucharest',
              'Greenland',                 'Prague',          'New_Caledonia',
                 'Bogota',                  'Seoul',               'Sarajevo',
             'Wellington',                'Bangkok',                 'Warsaw',
             'Copenhagen',              'Hong_Kong',            'Guadalajara',
           'Mid-Atlantic',               'Mazatlan',           'Buenos_Aires',
    'America/Los_Angeles',                 'Dublin',                 'Lisbon',
           'Newfoundland',              'Monterrey',                  'Tokyo',
        'America/Detroit',          'Midway_Island',               'Istanbul',
            'Solomon_Is.',       'America/Atikokan',               'Adelaide',
                'Nairobi',                    'EST',                   'Lima',
              'Islamabad',               'Helsinki',               'Pretoria',
    'West_Central_Africa',          'America/Boise',               'Canberra',
                  'Perth',                 'La_Paz']
Length: 86, dtype: str

In [16]:
pd.DataFrame({
    'NULL VALUES':df.isna().sum(),
    'UNIQUE VALUES':df.nunique(),
    'DTYPES':df.dtypes
})

                              NULL VALUES  UNIQUE VALUES   DTYPES
airline_sentiment                       0              3      str
airline_sentiment_confidence            0           1023  float64
negativereason                       5462             10      str
negativereason_confidence            4118           1410  float64
airline                                 0              6      str
retweet_count                           0             18    int64
tweet_coord                         13621            832      str
tweet_created                           0              9   object
tweet_location                       4733           3081      str
user_timezone                        4820             85      str
day_name                                0              7      str

In [17]:
df = df.drop(columns='tweet_location')

In [18]:
from sklearn.impute import KNNImputer
knn = KNNImputer(n_neighbors=10, weights='distance')

In [19]:
df.select_dtypes(include=['str']).columns

Index(['airline_sentiment', 'negativereason', 'airline', 'tweet_coord',
       'user_timezone', 'day_name'],
      dtype='str')

In [20]:
# using OHE
df_transformed = pd.get_dummies(df[['airline_sentiment', 'negativereason', 'airline', 'tweet_coord','user_timezone', 'day_name']])

In [ ]:
nulls = df['airline_sentiment', 'negativereason', 'airline', 'tweet_coord','user_timezone', 'day_name'].isna()

In [ ]:
df_transformed

,airline_sentiment_negative,airline_sentiment_neutral,airline_sentiment_positive,negativereason_Bad Flight,negativereason_Can't Tell,negativereason_Cancelled Flight,negativereason_Customer Service Issue,negativereason_Damaged Luggage,negativereason_Flight Attendant Complaints,negativereason_Flight Booking Problems,...,user_timezone_Warsaw,user_timezone_Wellington,user_timezone_West_Central_Africa,day_name_Friday,day_name_Monday,day_name_Saturday,day_name_Sunday,day_name_Thursday,day_name_Tuesday,day_name_Wednesday
0,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
3,True,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
4,True,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14635,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
14636,True,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,True,False,False,False
14637,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
14638,True,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,True,False,False,False
14639,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False

In [ ]:
# imputation on missing values

df_imputed = knn.fit_transform(df)
df_imputed

ValueError: could not convert string to float: 'neutral'

In [ ]:

# df.select_dtypes(include='str').columns

Index(['airline_sentiment', 'negativereason', 'airline', 'tweet_coord',
       'user_timezone', 'day_name'],
      dtype='str')

In [ ]:
df.sample(6)

,airline_sentiment,airline_sentiment_confidence,negativereason,negativereason_confidence,airline,retweet_count,tweet_coord,tweet_created,user_timezone,day_name
679,neutral,0.3433,NaN,0.0000,United,0,NaN,2015-02-24,Eastern_Time,Tuesday
7598,positive,0.6671,NaN,0.0000,Delta,0,NaN,2015-02-22,Eastern_Time,Sunday
11265,negative,1.0000,Customer Service Issue,1.0000,US Airways,0,NaN,2015-02-18,Eastern_Time,Wednesday
9510,negative,0.6739,Customer Service Issue,0.6739,US Airways,0,NaN,2015-02-23,Central_Time,Monday
6195,negative,0.6731,Cancelled Flight,0.6731,Southwest,0,NaN,2015-02-18,NaN,Wednesday
12461,negative,1.0000,Customer Service Issue,0.6194,American,0,NaN,2015-02-24,London,Tuesday

In [ ]:
# df.select_dtypes(include=['int','float']).columns

In [ ]:
# from sklearn.preprocessing import StandardScaler
# scaler = StandardScaler()

In [ ]:
df[['airline_sentiment_confidence', 'negativereason_confidence','retweet_count']] = scaler.fit_transform(df[['airline_sentiment_confidence', 'negativereason_confidence','retweet_count']])

In [ ]:
# df.sample(6)